spring:
  h2:
    console:
      path: /feign
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:userdb/feign
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
    show_sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:/sql/data.sql
#      schema-locations: classpath:/sql/schema.sql

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8090